### ISSUE TITLE
Ability to reference vite assets in yaml files

### ISSUE THREAD

**Issue by s2b** [s2b/vite-asset-collector#12]
To be able to generate CSS for the RTE in the backend, it should be possible to reference assets generated by vite in YAML files.

One possible solution would be to implement a VitePlaceholderProcessor as described here:
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/Configuration/Yaml/YamlApi.html#custom-placeholder-processing

In practice, this could look something like this:

```yaml
editor:
  config:
    contentsCss:
      # with default manifest file
      - %vite("EXT:my_extension/Resources/Private/Css/rte.css")%
      # with manifest path
      - %vite("EXT:my_extension/Resources/Private/Css/rte.css", "_assets/vite/manifest.json")%
```
