### ISSUE TITLE
Placeholder does not resolve

### ISSUE THREAD

**Issue by ochorocho** [s2b/vite-asset-collector#32]
The placeholder `%vite('assets/rte.css')%` does not return a CSS file as expected.

Ich returns only the `file` which is JS:
https://github.com/s2b/vite-asset-collector/blob/main/Classes/Service/ViteService.php#L139-L140

RteDefaultPreset.yaml
```yaml
editor:
  config:
    # Include custom CSS
    contentsCss: "%vite('assets/rte.css')%" # <<< DOES NOT RESOLVE
```

manifest.json
```js
...
  "assets/rte.js": {
    "assets": [
      "assets/Share-Regular-McM9bfXV.ttf"
    ],
    "css": [
      "assets/rte-jfN4x0Xs.css" # <<< NO IDEA, HOW TO GET THIS FILE
    ],
    "file": "assets/rte-4EM0ud4N.js",
    "isEntry": true,
    "src": "assets/rte.js"
  }
...
```

The issue reported for the TYPO3 Template repository:
https://gitlab.com/gitlab-org/project-templates/typo3-distribution/-/issues/23

<img width="2335" alt="Bildschirmfoto_2023-12-05_um_17 00 15" src="https://github.com/s2b/vite-asset-collector/assets/4623070/23208e16-8950-4069-8e32-8bb2681ba4b8">

**Comment by ochorocho** [comment]
To fix this issue do the following:

```yaml
editor:
  config:
    # Include custom CSS
    contentsCss: "%vite('assets/Scss/rte.scss')%"
```

```
const VITE_ENTRYPOINTS = [
  "assets/app.js",
  "assets/Scss/rte.scss", // Use the scss file as entrypoint instead of rte.js
];
```

For more details see https://github.com/vitejs/vite/issues/15161
